### PR TITLE
Added TV season limit

### PR DESCRIPTION
**Pull request by nwithan8**
I'm tired of someone requesting some long-running TV show through Mellow and me getting stuck with a 40-season long backlog when all they really want to watch is the latest season.
In settings, users can indicate the cut-off count (if a running show has more than _ seasons, only grab the latest one). tv.js updated to make an additional Ombi API call for show info, compares season count to user setting, and requests either allSeasons or latestSeason of show accordingly.

### CODE REVIEW

**Comment by v0idp** [comment]
please don't forget to add a migration file to migrations so everyones database gets migrated properly.

**Comment by nwithan8** [comment]
No idea how to do that.

**Comment by v0idp** [comment]
Check out the other sql files in there, it's not complicated to do

**Comment by Alpha5k** [comment]
My only concern is we would have to remove this change when we add the ability for users to request individual seasons. It's more of a stopgap

**Comment by nwithan8** [comment]
I'm already looking into how to request individual seasons. Is there a fork you've already started that? Don't want to start from scratch for no reason.

**Comment by v0idp** [comment]
@Alpha5K can you take a look at the conflict ?

**Comment by v0idp** [comment]
We can't merge this request due to the new way the database works now. If you want this feature still implemented. Please make a new PR request. thank you

**Pull request closed without merging**
