### PR TITLE
Added ability to monitor single channel, also includes db_migrations

### PR DESCRIPTION
**Pull request by ImDevinC**

### CODE REVIEW

**Comment by ImDevinC** [comment]
There's a small change here, but required some database changes as well. What this PR aims to do is allow an admin to specify a single channel the bot will listen to.
To store this configuration value in the SQL table, I added some database migrations which is a built-in feature of npm sqlite. This allows for easily upgrading/downgrading the database without needing to recreate it all the time.
Great utility so far, works great!

**Comment by Alpha5k** [comment]
I assume the bot will still listen in all channels if no channel name is provided?

**Comment by ImDevinC** [comment]
@AlphaHMD yep, that's the default on line 129 of bot.js. If nothing is provided, we return false (false here means don't block the message)

**Comment by ImDevinC** [comment]
The only thing I'm not a fan of is my downgrade in the migration, which just drops/recreates the bot table. My sqlite knowledge is limited, but from what I understand, it's not a trivial task to alter a table and remove a column. Unfortunately this means dropping all current data. However since it's just the first migration, perhaps this isn't a huge deal?

**Comment by v0idp** [comment]
I am still looking into a way to properly migrate the sqlite database. the idea is to basically dump the old db to memory and create a new db file with the changes and the old dump. But yea it's not trivial.

**Comment by ImDevinC** [comment]
Ok, fixed the migration aspect. Now instead of doing just dropping and recreating the table, the downward migration rename the existing table, create a new table, copy the existing settings (minutes the new column being added), and then drop the old table. This is much cleaner, and causes us to not lose the users data.

**Comment by ImDevinC** [comment]
Ok, made some updates that should make this much cleaner, curious to hear your feedback. Also, if this is too many changes in one PR, let me know and I can make this two separate PR's.

1. I moved the initial database creation to same migration process instead of using the `CREATE <TABLE> IF NOT EXIST ...` method. The db.migrate method is a documented method, and the initial schema like this is actually used an example on the [sqlite npm package site](https://www.npmjs.com/package/sqlite#migrations)
1. I also changed the (now) second migration to not just drop the bot table and recreate it, but rather rename the existing `bot` table, create a new `bot` table, copy the existing settings from the old table into the new one, and then drop the old one. This way the user settings aren't lost.

**Comment by v0idp** [comment]
This looks like a really good solution to our database migration issue we had. If you can add this change as a migration too I will definitely merge it. Thank you!

https://github.com/v0idp/Mellow/commit/193614eab30c328bd49d0ed580e343669fb49695

**Review by v0idp — CHANGES_REQUESTED** [review]
This looks like a really good solution to our database migration issue we had. If you can add this change as a migration too I will definitely merge it. Thank you!

https://github.com/v0idp/Mellow/commit/193614eab30c328bd49d0ed580e343669fb49695

**Comment by ImDevinC** [comment]
Thanks for the feedback @v0idp, I made the requested changes by adding the username migration as 002 and moving the channel migration to 003 just to keep things in the proper order of when they were completed in the code already.

**Review by v0idp — APPROVED** [review]
thank you for the additional code change. approved

**Pull request merged**
