### PR TITLE
Test API buttons

### LINKED ISSUE #55: Test API button in web configuration
Add a ``Test API`` Button to all 3rd party APIs to actually confirm that it works.

### PR DESCRIPTION
**Pull request by CalamityJames**
Fixes #55.

Tests the current API credentials for each system (Ombi, Tautulli, Sonarr and Radarr).

You have to save the changes before testing them, as it reads the config settings directly from the DB when testing.

Currently for Ombi it requests the `/api/v1/Search/movie/popular` endpoint as `/api/v1/Status/info` doesn't require an API key - if anyone can think of a better endpoint to use I'm open to suggestions!

I have tested this on my local install, all seems OK.

### CODE REVIEW

**Comment by v0idp** [comment]
Can you provide a screenshot of the button ?

**Comment by CalamityJames** [comment]
Might need some more styling, but I didn't want to mess around with the layout too much:

image

**Comment by v0idp** [comment]
move the Test API Button left next to Submit button

**Comment by CalamityJames** [comment]
How do these look, before I commit:

image

image

**Comment by v0idp** [comment]
much better!

**Pull request merged**
