### PR TITLE
Add repl.it compatibility

### PR DESCRIPTION
**Pull request by ghost**
This will let users run the bot for free with ease. 

https://repl.it/talk/learn/Configuring-GitHub-repos-to-run-on-Replit-and-contributing-back/23948

### CODE REVIEW

**Comment by v0idp** [comment]
I'm not happy with the README update. you seem to have added a game "2048" to the link.

**Comment by ghost** [comment]
Sorry. I appear to have forgotten how to read

**Comment by v0idp** [comment]
why is the run command empty when loaded into repl.it ?
also how does one access the web config in repl.it ?

**Comment by ghost** [comment]
You haven't accepted the pr. Try importing my fork into the a repl to see
how the run button would work

**Comment by v0idp** [comment]
Ah yes true. So what about the web config?

**Pull request merged**
